import utils

SIMILARITY_FUNCTION = utils.weight_similarity
SCORING_FUNCTION = utils.weighted_overlap

INCLUDE_NAMED_ENTITIES = True
POS = None

NORMALIZE_SCORES = True
MIN_VECTOR_LENGTH = 50
MAX_VECTOR_LENGTH = 1000